import Head from "next/head";
import React from 'react'
import NavbarWrap from '../components/navbar'
import styles from "@/styles/Career.module.css";

const Careers = () => {
    return (
        <>
            <Head>
                <title>Log Pose | Careers</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            
            <NavbarWrap />
            <div className = "pt-5">
                <div className="container mt-5 mb-3 justify-content-center">
                    <div className="row">
                        <div className="col-md-8">
                            <div className="card p-3 mb-2">
                                <div className="d-flex justify-content-between">
                                    <div className="d-flex flex-row align-items-center">
                                        <div className="icon"> <i className="bx bxl-mailchimp"></i> </div>
                                        <div className={`ms-2 ${styles.details}`}>
                                            <h6 className="mb-0">Mailchimp</h6> <span>1 days ago</span>
                                        </div>
                                    </div>
                                    <div className={styles.badge}> <span>Design</span> </div>
                                </div>
                                <div className="mt-5">
                                    <h3 className="heading">Senior Product<br />Designer-Singapore</h3>
                                     {/* Job description */}
                                    <p className="text-muted mt-2">
                                        We are looking for a talented designer to join our team to help build intuitive, beautiful, and user-friendly product interfaces for millions of users worldwide.
                                    </p>

                                    {/* Job details */}
                                    <div className="mt-3">
                                        <p><i className="bx bx-map"></i> Location: Singapore</p>
                                        <p><i className="bx bx-briefcase-alt"></i> Type: Full-time</p>
                                        <p><i className="bx bx-dollar-circle"></i> Salary: $80,000 - $100,000/year</p>
                                    </div>
                                    <div className="mt-5">
                                        <div className="progress">

                                        </div>
                                        <div className="mt-3"> <span className="text1">32 Applied <span className="text2">of 50 capacity</span></span> </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                       <div className="col-md-8">
                            <div className="card p-3 mb-2">
                                <div className="d-flex justify-content-between">
                                    <div className="d-flex flex-row align-items-center">
                                        <div className="icon"> <i className="bx bxl-mailchimp"></i> </div>
                                        <div className={`ms-2 ${styles.details}`}>
                                            <h6 className="mb-0">Mailchimp</h6> <span>1 days ago</span>
                                        </div>
                                    </div>
                                    <div className={styles.badge}> <span>Design</span> </div>
                                </div>
                                <div className="mt-5">
                                    <h3 className="heading">Senior Product<br />Designer-Singapore</h3>
                                     {/* Job description */}
                                    <p className="text-muted mt-2">
                                        We are looking for a talented designer to join our team to help build intuitive, beautiful, and user-friendly product interfaces for millions of users worldwide.
                                    </p>

                                    {/* Job details */}
                                    <div className="mt-3">
                                        <p><i className="bx bx-map"></i> Location: Singapore</p>
                                        <p><i className="bx bx-briefcase-alt"></i> Type: Full-time</p>
                                        <p><i className="bx bx-dollar-circle"></i> Salary: $80,000 - $100,000/year</p>
                                    </div>
                                    <div className="mt-5">
                                        <div className="progress">

                                        </div>
                                        <div className="mt-3"> <span className="text1">32 Applied <span className="text2">of 50 capacity</span></span> </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="col-md-8">
                            <div className="card p-3 mb-2">
                                <div className="d-flex justify-content-between">
                                    <div className="d-flex flex-row align-items-center">
                                        <div className="icon"> <i className="bx bxl-mailchimp"></i> </div>
                                        <div className={`ms-2 ${styles.details}`}>
                                            <h6 className="mb-0">Mailchimp</h6> <span>1 days ago</span>
                                        </div>
                                    </div>
                                    <div className={styles.badge}> <span>Design</span> </div>
                                </div>
                                <div className="mt-5">
                                    <h3 className="heading">Senior Product<br />Designer-Singapore</h3>
                                     {/* Job description */}
                                    <p className="text-muted mt-2">
                                        We are looking for a talented designer to join our team to help build intuitive, beautiful, and user-friendly product interfaces for millions of users worldwide.
                                    </p>

                                    {/* Job details */}
                                    <div className="mt-3">
                                        <p><i className="bx bx-map"></i> Location: Singapore</p>
                                        <p><i className="bx bx-briefcase-alt"></i> Type: Full-time</p>
                                        <p><i className="bx bx-dollar-circle"></i> Salary: $80,000 - $100,000/year</p>
                                    </div>
                                    <div className="mt-5">
                                        <div className="progress">

                                        </div>
                                        <div className="mt-3"> <span className="text1">32 Applied <span className="text2">of 50 capacity</span></span> </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
           
        </>
    )
}

export default Careers