import Head from "next/head";
import React from 'react'
import NavbarWrap from '../components/navbar'
import styles from "@/styles/Career.module.css";
import { FcBriefcase } from "react-icons/fc";
import { FcGlobe } from "react-icons/fc";
import { FcDebt } from "react-icons/fc";
import { BiSolidCube } from "react-icons/bi";
import ProgressBar from 'react-bootstrap/ProgressBar';

const Careers = () => {
    return (
        <>
            <Head>
                <title>Log Pose | Careers</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>

            <NavbarWrap />
            <div className="pt-5">
                <div className="container mt-5 mb-3 justify-content-center">
                    <div className="mb-5">
                        <h1 className="fw-bolder">Careers</h1>
                        <p className="lead fw-normal text-muted mb-2">Let's Build Something Great Together.</p>
                        <ProgressBar animated now={45} />
                    </div>
                    <div className="row">
                        <div className="col-md-8">
                            <div className="card p-3 mb-2">
                                <div className="d-flex justify-content-between">
                                    <div className="d-flex flex-row align-items-center">
                                        <div className={styles.icon}> <BiSolidCube /> </div>
                                        <div className={`ms-2 ${styles.details}`}>
                                            <h6 className="mb-0">Mailchimp</h6> <span>1 days ago</span>
                                        </div>
                                    </div>
                                    <div className={styles.badge}> <span>Design</span> </div>
                                </div>
                                <div className="mt-5">
                                    <h3 className="heading">Senior Product<br />Designer-Singapore</h3>
                                    {/* Job description */}
                                    <p className="text-muted mt-2">
                                        We are looking for a talented designer to join our team to help build intuitive, beautiful, and user-friendly product interfaces for millions of users worldwide.
                                    </p>

                                    {/* Job details */}
                                    <div className="mt-3">
                                        <p><FcGlobe /> Location: Singapore</p>
                                        <p><FcBriefcase /> Type: Full-time</p>
                                        <p><FcDebt /> Salary: $80,000 - $100,000/year</p>
                                    </div>
                                    <div className="d-flex justify-content-between mt-5">
                                        <div className="progres mt-2">
                                            <button className="btn btn-primary btn-sm" id="submitButton" type="submit">Apply</button>
                                        </div>
                                        <div className="mt-2"> <span className="text1">32 Applied <span className="text2">of 50 capacity</span></span> </div></div>
                                </div>
                            </div>
                        </div>
                        <div className="col-md-8">
                            <div className="card p-3 mb-2">
                                <div className="d-flex justify-content-between">
                                    <div className="d-flex flex-row align-items-center">
                                        <div className={styles.icon}> <BiSolidCube /> </div>
                                        <div className={`ms-2 ${styles.details}`}>
                                            <h6 className="mb-0">Mailchimp</h6> <span>1 days ago</span>
                                        </div>
                                    </div>
                                    <div className={styles.badge}> <span>Design</span> </div>
                                </div>
                                <div className="mt-5">
                                    <h3 className="heading">Senior Product<br />Designer-Singapore</h3>
                                    {/* Job description */}
                                    <p className="text-muted mt-2">
                                        We are looking for a talented designer to join our team to help build intuitive, beautiful, and user-friendly product interfaces for millions of users worldwide.
                                    </p>

                                    {/* Job details */}
                                    <div className="mt-3">
                                        <p><FcGlobe /> Location: Singapore</p>
                                        <p><FcBriefcase /> Type: Full-time</p>
                                        <p><FcDebt /> Salary: $80,000 - $100,000/year</p>
                                    </div>
                                    <div className="d-flex justify-content-between mt-5">
                                       <div className="progres mt-2">
                                            <button className="btn btn-primary btn-sm" id="submitButton" type="submit">Apply</button>
                                        </div>
                                        <div className="mt-2"> <span className="text1">32 Applied <span className="text2">of 50 capacity</span></span> </div></div>
                                </div>
                            </div>
                        </div>
                        <div className="col-md-8">
                            <div className="card p-3 mb-2">
                                <div className="d-flex justify-content-between">
                                    <div className="d-flex flex-row align-items-center">
                                        <div className={styles.icon}> <BiSolidCube /> </div>
                                        <div className={`ms-2 ${styles.details}`}>
                                            <h6 className="mb-0">Mailchimp</h6> <span>1 days ago</span>
                                        </div>
                                    </div>
                                    <div className={styles.badge}> <span>Design</span> </div>
                                </div>
                                <div className="mt-5">
                                    <h3 className="heading">Senior Product<br />Designer-Singapore</h3>
                                    {/* Job description */}
                                    <p className="text-muted mt-2">
                                        We are looking for a talented designer to join our team to help build intuitive, beautiful, and user-friendly product interfaces for millions of users worldwide.
                                    </p>

                                    {/* Job details */}
                                    <div className="mt-3">
                                        <p><FcGlobe /> Location: Singapore</p>
                                        <p><FcBriefcase /> Type: Full-time</p>
                                        <p><FcDebt /> Salary: $80,000 - $100,000/year</p>
                                    </div>
                                    <div className="d-flex justify-content-between mt-5">
                                        <div className="progres mt-2">
                                            <button className="btn btn-primary btn-sm" id="submitButton" type="submit">Apply</button>
                                        </div>
                                        <div className="mt-2"> <span className="text1">32 Applied <span className="text2">of 50 capacity</span></span> </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </>
    )
}

export default Careers