import Head from "next/head";
import React from 'react'
import NavbarWrap from '../components/navbar'
import styles from "@/styles/Home.module.css";
import { FaMapMarkedAlt } from "react-icons/fa";
import { SiGmail } from "react-icons/si";
import { FaLinkedin } from "react-icons/fa";
import { FaSquareXTwitter } from "react-icons/fa6";


const Contact = () => {
    return (
        <>
            <Head>
                <title>Log Pose | Contact Us</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>

            <NavbarWrap />

            <div className="pt-5 mt-auto">
                <section className="bg-light py-5">
                    <div className="container px-5">
                        <div className="row gx-5 justify-content-center">
                            <div className="col-xxl-8">
                                <div className="text-center my-5">
                                    <h2 className="display-5 fw-bolder"><span className="text-gradient d-inline">Let&#39;s Connect</span></h2>
                                    <p className="lead fw-light mb-4">We&#39;re more than a product company - we&#39;re your innovation partner</p>
                                    <p className="text-muted">At LogPose Instruments, we value collaboration and communication. Whether you&#39;re a researcher, engineer, partner, or just curious about our work in photonics instrumentation, we&#39;d love to hear from you. Have a technical question ? Looking for custom solutions ? Need a quote or datasheet ? Our team of experts is ready to assist you with timely and accurate support.</p>
                                    <div className="d-flex justify-content-center fs-2 gap-4">
                                        <a className="text-gradient" href="#!"><FaMapMarkedAlt /></a>
                                        <a className="text-gradient" href="#!"><SiGmail /></a>
                                        <a className="text-gradient" href="#!"><FaLinkedin /></a>
                                        <a className="text-gradient" href="#!"><FaSquareXTwitter /></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </>
    )
}

export default Contact