import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import NavbarWrap from "./components/navbar";
import Hero from "./components/hero"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Log Pose</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      {/* Nav Section Start */}
      <NavbarWrap />
      {/* Nav Section End */}

      {/* Hero Section Start */}
      <Hero />
      {/* Hero Section End */}
    </>
  );
}
